---

- hosts: all
  become: true
  tasks:

# Installing apache2 and php on Ubuntu

  - name: install apache2 and php package for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution_version == "Ubuntu"

#  Installing apache2 and php on CentOS

  - name: install apache2 and php package for CentOS 
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution_version == "CentOS"