---

- hosts: all
  become: true
  pre_tasks:

# Installing updates on all hosts
  - name: update repo cache (CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

# Creating roles
- hosts: all
  become: true
  roles:
    - base

- hosts: terraform_station 
  become: true
  roles:
    - terraform_station

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers