# Install unzip and terraform
- name: install unzip
  tags: unzip,terraform
  package:
    name: unzip
    
- name: install terraform
  tags: terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_darwin_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root   
